name: Secret Scanner

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for scanning

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run secret scanner
      run: |
        python secret_detector.py . --output scan_report.txt

    - name: Check for secrets
      run: |
        if [ -s scan_report.txt ] && [ "$(cat scan_report.txt)" != "No secrets found." ]; then
          echo "::error::Potential secrets found in the repository. Please check scan_report.txt for details."
          exit 1
        fi

    - name: Upload scan report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: secret-scan-report
        path: scan_report.txt 